language: java
jdk:
  - oraclejdk8
install:
  - mvn --settings .travis/settings.xml install -B -V
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      repo: devialab/lib-mongodb
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    on:
      repo: devialab/lib-mongodb
      tags: true
      jdk: oraclejdk8